### ISSUE TITLE
메인 페이지에 포함되어야 할것

### ISSUE THREAD

**Issue by sukso96100** [skhu-sw/skhu-sw.github.io#1]
메인 페이지에 포함되어야 할것

- [x] 위키로 이동하는 버튼
- [x] 블로그로 이동하는 버튼
- [x] 튜토리얼로 이동하는 버튼
- [x] 슬랙 가입 버튼
- [x] 슬랙 입장 버튼
- [x] 깃허브 이동 버튼
- [x] 학교 홈페이지 버튼
- [x] 학과 홈페이지 버튼

**Comment by junshoong** [comment]
최근 커밋(9f73792)을 통해 모든 항목을 처리했으므로 이슈를 닫도록 하겠습니다.
